import React,{useState}from'react';
import{ClipboardList,Plus,Truck,Building2,Mountain,Package,UserCheck,CheckCircle2,Clock3,Copy,Check,Trash2,Edit2,MapPin,Users,Route,Gauge,ArrowLeft,RefreshCw}from'lucide-react';
import{DailyOrder,FleetTruck,TripLoad,Quarry,ClientFactory}from'../types/fleet';
interface AdminDashboardProps{orders:DailyOrder[];trucks:FleetTruck[];trips:TripLoad[];quarries:Quarry[];clients:ClientFactory[];onOpenNewLoadModal:()=>void;onAssignDriver:(o:string,t:string)=>void;onUpdateOrderNotes:(o:string,n:string)=>void;onDeleteOrder:(o:string)=>void;onChangeTripDestination:(tripId:string,factoryName:string,factoryCoords:{lat:number;lng:number},reason:'quality_rejection'|'factory_closed'|'dispatch_instruction'|'other',notes?:string)=>void;onSendDriverAlert:(d:string,t:string,m:string)=>void}
export const AdminDashboard:React.FC<AdminDashboardProps>=({orders,trucks,trips,quarries,clients,onOpenNewLoadModal,onAssignDriver,onUpdateOrderNotes,onDeleteOrder,onChangeTripDestination})=>{
 const[notesId,setNotesId]=useState<string|null>(null),[notes,setNotes]=useState(''),[copied,setCopied]=useState(false),[filter,setFilter]=useState('all'),[changeTripId,setChangeTripId]=useState<string|null>(null),[changeFactory,setChangeFactory]=useState(''),[changeReason,setChangeReason]=useState<'quality_rejection'|'factory_closed'|'dispatch_instruction'|'other'>('quality_rejection'),[changeNotes,setChangeNotes]=useState('');
 const required=orders.reduce((s,o)=>s+o.totalRequiredLoads,0),done=orders.reduce((s,o)=>s+o.completedLoads,0),active=trips.filter(t=>t.status!=='delivered').length,remain=Math.max(0,required-done),pct=required?Math.min(100,Math.round(done/required*100)):0;
 const materials=Array.from(new Set(orders.map(o=>o.material))),shown=filter==='all'?orders:orders.filter(o=>o.material===filter);
 const copy=()=>{navigator.clipboard.writeText(orders.map((o,i)=>`${i+1}. ${o.factoryName} | ${o.quarryName} | ${o.material} | ${o.totalRequiredLoads} نقلة`).join('\\n'));setCopied(true);setTimeout(()=>setCopied(false),2000)};
 const flow=[['01','طلب التحميل',ClipboardList,'from-blue-600 to-cyan-500'],['02','قائمة الانتظار',Users,'from-violet-600 to-fuchsia-500'],['03','التخصيص',UserCheck,'from-indigo-600 to-blue-500'],['04','السائق',Truck,'from-orange-500 to-amber-400'],['05','التنفيذ',Route,'from-blue-600 to-sky-400'],['06','التسليم',CheckCircle2,'from-emerald-600 to-green-400']]as const;
 return <div dir="rtl" className="space-y-5 pb-8">
  <section className="relative overflow-hidden rounded-3xl border border-blue-900/60 bg-gradient-to-br from-[#102b50] via-[#0b1e3a] to-[#071322] p-6 shadow-2xl">
   <div className="absolute -left-16 -top-20 h-52 w-52 rounded-full bg-cyan-400/10 blur-3xl"/>
   <div className="relative flex flex-col lg:flex-row lg:items-end justify-between gap-5">
    <div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-[11px] font-bold text-emerald-300"><i className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/>مركز التشغيل المباشر</div><h1 className="text-2xl sm:text-4xl font-black text-white">التدفق التشغيلي <span className="text-cyan-300">(المحدث)</span></h1><p className="mt-2 text-sm text-slate-300">من طلب التحميل اليومي إلى التسليم النهائي — كل مرحلة واضحة وقابلة للمتابعة.</p></div>
    <button onClick={onOpenNewLoadModal} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-amber-400 px-5 py-3 text-sm font-black text-slate-950 shadow-lg"><Plus className="h-5 w-5"/>إنشاء طلب تحميل</button>
   </div>
  </section>
  <section className="grid grid-cols-2 xl:grid-cols-5 gap-3">
   {[['إجمالي الطلبات',orders.length,'طلب',ClipboardList,'text-cyan-300'],['إجمالي النقلات',required,'نقلة',Package,'text-blue-300'],['جارية الآن',active,'تريلا',Truck,'text-orange-300'],['متبقي للتنفيذ',remain,'نقلة',Clock3,'text-violet-300'],['تم التسليم',done,'نقلة',CheckCircle2,'text-emerald-300']].map(([l,v,u,I,c]:any)=><div key={l} className="rounded-2xl border border-slate-700/70 bg-[#0e1929] p-4 shadow-lg"><div className="flex justify-between"><span className={`rounded-xl bg-slate-950/60 p-2 ${c}`}><I className="h-5 w-5"/></span><span className="text-[11px] text-slate-400">{l}</span></div><div className={`mt-3 text-3xl font-black ${c}`}>{v}</div><div className="text-[10px] text-slate-500">{u}</div></div>)}
  </section>
  <section className="rounded-3xl border border-slate-700/70 bg-[#0b1422] p-4 shadow-xl"><div className="mb-4 flex justify-between"><div><h2 className="font-black text-white text-lg">مسار التشغيل</h2><p className="text-xs text-slate-400">الرحلة التشغيلية من الطلب إلى إغلاق الحمولة</p></div><span className="text-xs text-slate-400">إنجاز اليوم <b className="text-emerald-300">{pct}%</b></span></div><div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-2">{flow.map(([n,t,I,g],i)=><div key={n} className="relative rounded-2xl border border-slate-700/60 bg-[#101b2c] p-3"><div className={`mb-2 flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br ${g} text-white`}><I className="h-5 w-5"/></div><div className="text-[9px] text-slate-500">{n}</div><div className="text-sm font-black text-white">{t}</div>{i<5&&<ArrowLeft className="hidden xl:block absolute -left-3 top-1/2 h-5 w-5 text-slate-500 z-10"/>}</div>)}</div></section>
  <section className="grid xl:grid-cols-[1.7fr_1fr] gap-5">
   <div className="rounded-3xl border border-slate-700/70 bg-[#0b1422] overflow-hidden shadow-xl">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700/60 bg-[#0e1929] p-4"><div><h2 className="flex items-center gap-2 font-black text-white"><ClipboardList className="h-5 w-5 text-cyan-300"/>أوامر التحميل اليومية</h2><p className="text-[10px] text-slate-400 mt-1">Daily Dispatch Board</p></div><div className="flex gap-2"><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-xs text-slate-200"><option value="all">كل المواد والخامات</option>{materials.map(m=><option key={m}>{m}</option>)}</select><button onClick={copy} className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-300">{copied?<Check className="inline h-4 w-4"/>:<Copy className="inline h-4 w-4"/>} كشف واتساب</button></div></div>
    <div className="p-4 space-y-3">{shown.map(o=>{const r=Math.max(0,o.totalRequiredLoads-o.completedLoads),p=o.totalRequiredLoads?Math.min(100,Math.round(o.completedLoads/o.totalRequiredLoads*100)):0;return <article key={o.id} className="rounded-2xl border border-slate-700/70 bg-[#101a29] p-4 hover:border-cyan-500/40 transition"><div className="flex flex-wrap justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-gradient-to-br from-orange-500 to-amber-400 px-3 py-2 text-xs font-black text-slate-950">{o.material}</span><div><div className="font-black text-white">{o.factoryName}</div><div className="text-[10px] text-slate-400">{o.clientName} · {o.quarryName}</div></div></div><button onClick={()=>onDeleteOrder(o.id)} className="text-slate-500 hover:text-red-300"><Trash2 className="h-4 w-4"/></button></div><div className="mt-4 grid md:grid-cols-3 gap-2"><div className="rounded-xl border border-slate-700/60 bg-slate-950/40 p-3"><div className="text-[10px] text-orange-300"><Mountain className="inline h-4 w-4 ml-1"/>المحجر</div><b className="text-sm text-white">{o.quarryName}</b></div><div className="rounded-xl border border-slate-700/60 bg-slate-950/40 p-3"><div className="text-[10px] text-cyan-300"><Building2 className="inline h-4 w-4 ml-1"/>المصنع</div><b className="text-sm text-white">{o.factoryName}</b></div><div className="rounded-xl border border-slate-700/60 bg-slate-950/40 p-3"><div className="text-[10px] text-violet-300"><UserCheck className="inline h-4 w-4 ml-1"/>السائق</div><b className="text-sm text-white">{o.assignedDriverName||'تخصيص تلقائي'}</b><div className="text-[10px] text-slate-500">{o.assignedTruckPlate||'حسب قائمة الانتظار'}</div></div></div><div className="mt-4"><div className="flex justify-between text-[10px] text-slate-400"><span>التقدم</span><b>{o.completedLoads}/{o.totalRequiredLoads} · متبقي {r}</b></div><div className="mt-1 h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full bg-gradient-to-r from-blue-500 to-emerald-400" style={{width:`${p}%`}}/></div></div><div className="mt-3 flex flex-wrap justify-end gap-2">
<select value={trucks.find(t=>t.driverId===o.assignedDriverId)?.id||''} onChange={e=>onAssignDriver(o.id,e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-[10px] text-slate-300"><option value="">تخصيص / تغيير السائق</option>{trucks.map(t=><option key={t.id} value={t.id}>{t.driverName} - {t.plateNumber}</option>)}</select>
{trips.filter(t=>t.dailyOrderId===o.id&&t.status!=='delivered'&&t.status!=='cancelled').map(t=><button key={t.id} onClick={()=>{setChangeTripId(t.id);setChangeFactory('');setChangeNotes('')}} className="inline-flex items-center gap-1 rounded-xl border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-[10px] font-bold text-amber-300"><RefreshCw className="h-3 w-3"/>تحويل وجهة</button>)}
</div>
{changeTripId&&<div className="mt-3 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3">
<div className="text-xs font-black text-amber-300">تحويل وجهة النقلة</div>
<div className="mt-2 grid gap-2">
<select value={changeFactory} onChange={e=>setChangeFactory(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 p-2 text-xs text-white"><option value="">اختر المصنع الجديد</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
<select value={changeReason} onChange={e=>setChangeReason(e.target.value as typeof changeReason)} className="rounded-xl border border-slate-700 bg-slate-950 p-2 text-xs text-white"><option value="quality_rejection">رفض جودة</option><option value="factory_closed">المصنع مغلق</option><option value="dispatch_instruction">تعليمات تشغيل</option><option value="other">سبب آخر</option></select>
<textarea value={changeNotes} onChange={e=>setChangeNotes(e.target.value)} placeholder="ملاحظات التحويل" className="rounded-xl border border-slate-700 bg-slate-950 p-2 text-xs text-white"/>
<div className="flex gap-2"><button onClick={()=>{const f=clients.find(c=>c.id===changeFactory);if(!f)return;onChangeTripDestination(changeTripId,f.name,f.location,changeReason,changeNotes);setChangeTripId(null)}} className="rounded-xl bg-amber-500 px-3 py-2 text-xs font-black text-slate-950">تأكيد التحويل</button><button onClick={()=>setChangeTripId(null)} className="rounded-xl border border-slate-700 px-3 py-2 text-xs text-slate-300">إلغاء</button></div>
</div></div>}<div className="mt-3 rounded-xl bg-slate-950/30 p-3"><div className="flex justify-between text-[10px] font-bold text-slate-300"><span>تعليمات التشغيل</span><button onClick={()=>{setNotesId(notesId===o.id?null:o.id);setNotes(o.notes||'')}} className="text-cyan-300"><Edit2 className="inline h-3 w-3"/> تعديل</button></div>{notesId===o.id?<div className="mt-2 flex gap-2"><textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} className="flex-1 rounded-xl bg-slate-950 border border-slate-700 p-2 text-xs text-white"/><button onClick={()=>{onUpdateOrderNotes(o.id,notes);setNotesId(null)}} className="rounded-xl bg-cyan-500 px-3 text-xs font-black text-slate-950">حفظ</button></div>:<p className="mt-2 text-[10px] text-slate-400">{o.notes||'لا توجد تعليمات خاصة.'}</p>}</div></article>})}</div>
   </div>
   <div className="space-y-5">
    <div className="rounded-3xl border border-slate-700/70 bg-[#0b1422] overflow-hidden shadow-xl"><div className="border-b border-slate-700/60 bg-[#0e1929] p-4"><h2 className="flex items-center gap-2 font-black text-white"><MapPin className="h-5 w-5 text-emerald-300"/>التشغيل المباشر</h2><p className="text-[10px] text-slate-400">مؤشرات السائقين والنقلات الحالية</p></div><div className="relative h-64 bg-[#0d2130] overflow-hidden"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(#5eead4 1px,transparent 1px),linear-gradient(90deg,#5eead4 1px,transparent 1px)',backgroundSize:'32px 32px'}}/><div className="absolute inset-5 rounded-[40%] border border-emerald-400/30 bg-emerald-400/5"/>{trucks.slice(0,8).map((t,i)=><div key={t.id} className="absolute" style={{left:`${10+(i*19)%78}%`,top:`${15+(i*27)%65}%`}}><div className="h-9 w-9 rounded-full border-2 border-white/80 bg-blue-500 flex items-center justify-center shadow-lg"><Truck className="h-4 w-4 text-white"/></div><span className="absolute top-9 right-1/2 translate-x-1/2 text-[8px] whitespace-nowrap text-slate-300">{t.plateNumber}</span></div>)}</div><div className="grid grid-cols-3 gap-2 p-3">{[['متاح',trucks.filter(t=>t.status==='متاح للتحميل').length,'text-emerald-300'],['في التشغيل',active,'text-blue-300'],['الأسطول',trucks.length,'text-orange-300']].map(([l,v,c]:any)=><div className="rounded-xl bg-slate-950/50 p-3 text-center" key={l}><b className={`block text-lg ${c}`}>{v}</b><span className="text-[9px] text-slate-500">{l}</span></div>)}</div></div>
    <div className="rounded-3xl border border-slate-700/70 bg-[#0b1422] p-4 shadow-xl"><h2 className="mb-3 font-black text-white">ملخص التشغيل</h2>{[['طلبات',orders.length,ClipboardList,'text-cyan-300'],['جارية',active,Route,'text-orange-300'],['تم التسليم',done,CheckCircle2,'text-emerald-300'],['الإنجاز',`${pct}%`,Gauge,'text-violet-300']].map(([l,v,I,c]:any)=><div key={l} className="mb-2 flex items-center justify-between rounded-xl border border-slate-700/50 bg-slate-950/30 p-3"><span className="flex items-center gap-2 text-xs text-slate-300"><I className={`h-4 w-4 ${c}`}/>{l}</span><b className={`text-lg ${c}`}>{v}</b></div>)}</div>
   </div>
  </section>
  <section className="grid md:grid-cols-3 gap-4">{[['المحاجر',quarries.length,Mountain,'text-orange-300'],['المصانع',clients.length,Building2,'text-cyan-300'],['نسبة الإنجاز',`${pct}%`,Gauge,'text-emerald-300']].map(([l,v,I,c]:any)=><div key={l} className="rounded-2xl border border-slate-700/70 bg-[#0b1422] p-4"><div className="flex justify-between"><b className="text-white">{l}</b><I className={`h-5 w-5 ${c}`}/></div><div className={`mt-3 text-3xl font-black ${c}`}>{v}</div><div className="text-[10px] text-slate-500">بيانات تشغيلية</div></div>)}</section>
 </div>
}