-- Register a vehicle and its owner; vehicle_code is generated by the database.
ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS vehicle_code text;

CREATE UNIQUE INDEX IF NOT EXISTS vehicles_vehicle_code_unique
  ON public.vehicles (lower(btrim(vehicle_code)))
  WHERE vehicle_code IS NOT NULL AND btrim(vehicle_code) <> '';

CREATE SEQUENCE IF NOT EXISTS public.vehicle_code_seq START WITH 1;

CREATE OR REPLACE FUNCTION public.create_operational_vehicle(
  p_plate_number text,
  p_owner_name text,
  p_owner_phone text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_owner_id uuid;
  v_vehicle_id uuid;
  v_code text;
  v_plate text := NULLIF(btrim(p_plate_number), '');
  v_owner text := NULLIF(btrim(p_owner_name), '');
  v_phone text := NULLIF(btrim(p_owner_phone), '');
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.app_users au
    JOIN public.user_roles ur ON ur.user_id = au.user_id
    JOIN public.roles r ON r.role_id = ur.role_id
    WHERE au.auth_user_id = v_uid AND au.is_active = true
      AND r.name IN ('ADMIN', 'HEAD_OFFICE', 'BRANCH')
  ) THEN RAISE EXCEPTION 'INSUFFICIENT_ROLE'; END IF;

  IF v_plate IS NULL OR v_owner IS NULL THEN
    RAISE EXCEPTION 'REQUIRED_FIELDS_MISSING';
  END IF;

  IF EXISTS (SELECT 1 FROM public.vehicles
             WHERE lower(btrim(plate_number)) = lower(v_plate)) THEN
    RAISE EXCEPTION 'VEHICLE_PLATE_EXISTS';
  END IF;

  SELECT owner_id INTO v_owner_id
  FROM public.vehicle_owners
  WHERE lower(btrim(name)) = lower(v_owner)
    AND is_active = true
    AND ((v_phone IS NULL AND phone IS NULL) OR phone = v_phone)
  ORDER BY owner_id LIMIT 1;

  IF v_owner_id IS NULL THEN
    INSERT INTO public.vehicle_owners(name, phone, is_active)
    VALUES (v_owner, v_phone, true)
    RETURNING owner_id INTO v_owner_id;
  END IF;

  LOOP
    v_code := 'VH-' || lpad(nextval('public.vehicle_code_seq')::text, 6, '0');
    EXIT WHEN NOT EXISTS (
      SELECT 1 FROM public.vehicles
      WHERE lower(btrim(vehicle_code)) = lower(v_code)
    );
  END LOOP;

  INSERT INTO public.vehicles(plate_number, vehicle_code, owner_id, is_active)
  VALUES (v_plate, v_code, v_owner_id, true)
  RETURNING vehicle_id INTO v_vehicle_id;

  RETURN jsonb_build_object(
    'success', true, 'vehicle_id', v_vehicle_id,
    'vehicle_code', v_code, 'plate_number', v_plate,
    'owner_id', v_owner_id, 'owner_name', v_owner
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.create_operational_vehicle(text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_operational_vehicle(text, text, text) TO authenticated;

-- Refresh PostgREST's schema cache so the RPC is discoverable.
NOTIFY pgrst, 'reload schema';
